### ISSUE TITLE
[FEATURE] Offer possibility to add values for additional table-fields.

### ISSUE THREAD

**Issue by DavidBruchmann** [eliashaeussler/typo3-form-consent#62]
### Is your feature request related to a problem?

When the consent table is saved it's currently not possible to fill additional table fields. The existing Event Handlers never offer a solution for this challenge.

### Describe the solution you'd like

I'd like a configuration option to fill additional table fields (not in the data-field) per yaml configuration.

### Additional context

Example for using additional table fields, my desire is not only related to images but different fields too.

![image](https://user-images.githubusercontent.com/999146/174793470-e4d66072-2a9c-4326-a97b-0167ac1e2bd2.png)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct.

**Comment by eliashaeussler** [comment]
@DavidBruchmann Thanks for your issue.

The `ConsentFinisher` is designed to provide only two core functionalities: Persisting all form element values and sending an appropriate consent mail. It's meant to keep slim and extensible. That means, extended functionality should be added by an appropriate event listener for one of the dispatched events (see https://github.com/eliashaeussler/typo3-form-consent#events). 

What you're describing seems like extended functionality to me. Therefore, it should not be part of the core implementation. However, currently it's not that easy to extend a `Consent` with additional data from the current `FormRuntime`. That's why I added the `FormRuntime` object to all relevant events, see

- #65

With this PR, you can now access all form element values in an appropriate event listener. I will release this soonish.

**Comment by eliashaeussler** [comment]
Released with [`0.6.0`](https://github.com/eliashaeussler/typo3-form-consent/releases/tag/0.6.0).

**Comment by DavidBruchmann** [comment]
Thanks a lot!
