### ISSUE TITLE
[FEATURE] change mail layout

### ISSUE THREAD

**Issue by DavidBruchmann** [eliashaeussler/typo3-form-consent#63]
### Is your feature request related to a problem?

The system mail template includes logo, copyright and legal advises related to TYPO3 itself.
Sending any emails to website users never have to include these things and are rather distracting.

### Describe the solution you'd like

Use another Mail Layout, perhaps an own one.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by eliashaeussler** [comment]
@DavidBruchmann Thanks for your issue.

EXT:form_consent makes use of the `FluidEmail` component provided by TYPO3. This allows consistent mail layouts across the system.

However, if you don't want to use this layout, you are free to overwrite all layouts, templates and partials as described in https://github.com/eliashaeussler/typo3-form-consent#open_file_folder-configuration.

Since this is something I'm not planning to change, I'll close this issue.
