### ISSUE TITLE
[BUG]Errormessage after installation 

### ISSUE THREAD

**Issue by frank41263** [eliashaeussler/typo3-form-consent#75]
### TYPO3 version

11.5.2

### PHP version

7.4

### Extension version

0.6.3

### Composer mode

- [ ] I'm running TYPO3 in composer mode.

### Operating system

linux Ionos

### Current behavior

after installation the extention , i get this message after conform my inputs 

maybe i forgot something at the installation , i read your guide , but ... 

(1/1) #1257246929 TYPO3Fluid\Fluid\View\Exception\InvalidTemplateResourceException

Tried resolving a template file for controller action "Standard->consentMail" in format ".html", but none of the paths contained the expected template file (Standard/ConsentMail.html). The following paths were checked: /kunden/homepages/15/d612814826/htdocs/SVS_TYPO11/typo3/sysext/core/Resources/Private/Templates/Email/, /kunden/homepages/15/d612814826/htdocs/SVS_TYPO11/typo3/sysext/backend/Resources/Private/Templates/Email/

### Expected behavior

(1/1) #1257246929 TYPO3Fluid\Fluid\View\Exception\InvalidTemplateResourceException

Tried resolving a template file for controller action "Standard->consentMail" in format ".html", but none of the paths contained the expected template file (Standard/ConsentMail.html). The following paths were checked: /kunden/homepages/15/d612814826/htdocs/SVS_TYPO11/typo3/sysext/core/Resources/Private/Templates/Email/, /kunden/homepages/15/d612814826/htdocs/SVS_TYPO11/typo3/sysext/backend/Resources/Private/Templates/Email/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by eliashaeussler** [comment]
Hi @frank41263, did you include the TypoScript setup as written [here](https://github.com/eliashaeussler/typo3-form-consent#open_file_folder-configuration)?

> The TypoScript setup under `EXT:form_consent/Configuration/TypoScript` needs to be included and the required database changes need to be made.

**Comment by eliashaeussler** [comment]
Hi @frank41263, since TYPO3 is an english-speaking community, I kindly ask you to write comments in English.

Looking at your last comment, it seems to me that you lack a basic understanding when using Extbase plugins. I recommend you take a look at https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/TopLevelObjects/Plugin.html#properties-for-all-frontend-plugins-based-on-extbase for a short introduction about how to configure Extbase plugins.

In short:

* `plugin.tx_formconsent.persistence.storagePid` defines the **folder or page in your page tree** where to **store new consents**. This must not automatically be the same page where the consent plugin is located, but it depends on your setup.
* `plugin.tx_formconsent.view.templateRootPath` defines the template root path (normally in your sitepackage or other custom extension) where **template overrides of the default form_consent templates** are stored. This is **optional** as long as there's no need to override the default templates. Example: `EXT:my_sitepackage/Resources/Private/Templates/FormConsent`
* `plugin.tx_formconsent.view.partialRootPath` defines the root path of **partials overriding the default partials** from EXT:form_consent. Again, this is only needed if you actually need to override the default partials. Example: `EXT:my_sitepackage/Resources/Private/Partials/FormConsent`
* `plugin.tx_formconsent.view.layoutRootPath` defines the root path of **layouts overriding the default layouts** from EXT:form_consent. Example: `EXT:my_sitepackage/Resources/Private/Layouts/FormConsent`

All this is already described at https://github.com/eliashaeussler/typo3-form-consent#typoscript.

Apart from that, I'll ask again: Did you include the TypoScript setup as written [here](https://github.com/eliashaeussler/typo3-form-consent#open_file_folder-configuration)? This is an essential step to make EXT:form_consent plugins work in Frontend.

**Comment by eliashaeussler** [comment]
Closing due to lack of feedback.
